/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ruangong_process_html_and_pdf */

#ifndef _Included_ruangong_process_html_and_pdf
#define _Included_ruangong_process_html_and_pdf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ruangong_process_html_and_pdf
 * Method:    connect
 * Signature: ()I
 */

/*
 * Class:     ruangong_process_html_and_pdf
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */

/*
 * Class:     ruangong_process_html_and_pdf
 * Method:    process
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_ruangong_process_1html_1and_1pdf_process
  (JNIEnv *, jobject, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
